spring:
  profiles:
      active:
        - cat
        - ES
        - dev
guru:
  username: YmlUsername
  password: YmlPassword
  jdbcurl: YmlDBUrl

---

spring:
  profiles: prod
guru:
  username: YmlProdUsername
  password: YmlProdPassword
  jdbcurl: YmlProdDBUrl
